### ISSUE TITLE
fatsecret3L throwing error in API call of method getFoodEntry

### ISSUE THREAD

**Issue by bbrewington** [wilsontom/fatsecretR#9]
I may be reading this wrong, but is this correct?  There's nothing inside the match.call() function calls https://github.com/wilsontom/fatsecretR/blob/7a4e662fa4b02859c500474d4e4d9412f123836e/R/fatsecretR-method.R#L12-L13

I thought this might be the cause of the error I'm getting when I run the following code:

```R
# Set up authorization with 3 legged authentication
newAuth("BrentB")
APIkeys(BrentB, ConsumerKey = [INSERT CONSUMER KEY], 
        SharedSecret = [INSERT SHARED SECRET])
BrentB <- RequestAuthorisation(BrentB, params = "oob")
# go to link in slot "user_request_url" and 1) click allow; 2) copy pin # to clipboard
# pin in this case: 6628062
BrentB <- AuthoriseUser(BrentB, params = "6628062")
# At this point, the object BrentB is of class "fatsecret3L"

fatsecretR(object = BrentB, method = "getFoodEntry", param = "2017-10-21")
#>Error in (function (classes, fdef, mtable)  : 
#>  unable to find an inherited method for function ‘fatsecretR’ for signature ‘"fatsecret3L"’
```

**Comment by wilsontom** [comment]
I think I can see what has gone wrong here, and it's mainly caused by my lack of proper documentation, apologies for that. 

The `fatsecret3L` object which for you is named `BrentB` is effectively just a "holding object" but never needs to get passed to a method. So everything you have done up to `BrentB <- AuthoriseUser(BrentB, params = "6628062")` is correct. 

When you loaded the fatsecretR library, a `S4` object named `fatsecret` will have been assigned to the global environment. You need to add your own API keys to this object as well;

```R
APIkeys(fatsecret, ConsumerKey = [INSERT CONSUMER KEY], 
        SharedSecret = [INSERT SHARED SECRET])
```

Then once you have obtained a token and secret for your delegated user following 3-Legged Authentication the `fatsecretR` method should look like this;

```R
fatsecretR(object = fatsecret, method = "getFoodEntry", param = "2017-10-21", BrentB_ConsumerKey, BrentB_Secret)
```
I am well aware that this is not the optimal way of doing any of this, it was very much a way of getting things up and running while trying to navigate the `fatsecret` API. My aim is to re-write this in the near future and make use of database connections (ie; `MySQL` or `sqlite`) for handling all the API keys.

Any feedback is always appreciated. 

Thanks
Tom

**Comment by bbrewington** [comment]
Thanks for the quick response!  Thought I'd share a complete workflow for completeness of documentation.  Something you might want to note in the help docs is that the `fatsecret3L` object's purpose is to hold authentication details such as `user_token` and `user_secret`, which are then passed along to the `fatsecretR` function.  That's the piece I wasn't understanding at first.

```R
newAuth(user_3legged)
APIkeys(user_3legged, [YOUR_CONSUMER_KEY], [YOUR_SHARED_SECRET])
APIkeys(fatsecret, [YOUR_CONSUMER_KEY], [YOUR_SHARED_SECRET])
user_3legged <- RequestAuthorisation(user_3legged, params = "oob")
user_3legged@user_request_url
# in a browser, navigate to the link the above line outputs to the console, and click the "allow" button.
# Copy this number to the clipboard...referred to below as [YOUR_PIN]

user_3legged <- AuthoriseUser(user_3legged, params = [YOUR_PIN])

user_token_raw <- stringr::str_extract(user_3legged@user_token, "(?<=\\=).+$")
user_secret_raw <- stringr::str_extract(user_3legged@user_secret, "(?<=\\=).+$")

fatsecretR(object = fatsecret, method = "getFoodEntry", 
                param = "2017-10-25", 
                user_token = user_token_raw,
                user_secret = user_secret_raw)
```
